### ISSUE TITLE
Releases folder missing?

### ISSUE THREAD

**Issue by nab128** [yyamasak/TkSQLite-Cipher#2]
Hi and thank you for continuing this project. Would like to download binary exe file if possible. Thanks.

**Comment by yyamasak** [comment]
Here is binary executable. I'm happy if it works for you.

https://github.com/yyamasak/TkSQLite-Cipher/releases/tag/0.9.19

![image](https://user-images.githubusercontent.com/52265/110088668-8011f300-7dd8-11eb-826d-23dd9571e1f1.png)
